version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    assignees:
      - "renehezser"

  - package-ecosystem: docker
    directory: /modules/FilterModule
    schedule:
      interval: daily
    groups:
      docker-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    assignees:
      - "renehezser"

  - package-ecosystem: nuget
    directory: /modules/FilterModule
    schedule:
      interval: daily
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    assignees:
      - "renehezser"
