name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # find the version
    - name: JSON to variables
      uses: antifree/json-to-variables@v1.0.1
      with:
        filename: './modules/FilterModule/module.json'
        prefix: module
    - name: Show output
      run: echo "The module version is ${{ env.module_image_tag_version }}"

    # build and push images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ReneHezser
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCRPAT }}
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: "./modules/FilterModule/"
        file: ./modules/FilterModule/Dockerfile
        platforms: linux/amd64 #,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:${{ env.module_image_tag_version }}
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:${{ env.module_image_tag_version }}-amd64
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:latest