name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ReneHezser
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCRPAT }}
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: "./modules/FilterModule/"
        file: ./modules/FilterModule/Dockerfile
        platforms: linux/amd64 #,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:${{ github.run_number }}
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:1.0.0-amd64
          ghcr.io/renehezser/edge-filter-blob-solution/filtermodule:latest